set nocompatible
set smartindent
set backspace=indent,eol,start
"set statusline=%F%m%r%h%w\[POS=%l,%v][%p%%]\%{strftime(\"%d/%m/%y\-\ %H:%M\")}
set statusline=%F%m%r%h%w\[pos=%l,%v][%p%%]
set number
"set cursorline
set ruler
set et
set tabstop=4
"set softtabstop=4
set shiftwidth=4
"set expandtab
filetype plugin indent on
set ignorecase smartcase
set noerrorbells
set showmatch
set hlsearch
set showcmd
set scrolloff=3
set noswapfile
"set incsearch
"set laststatus=2
"set autoindent
"set autochdir 
set cursorline
set term=xterm
set autoread
set nowrapscan
"set clipboard=unnamed


"Taglist
let Tlist_Ctags_Cmd="/usr/bin/ctags"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1 
let Tlist_WinWidth=40
"let g:winManagerWindowLayout='FileExplorer|TagList'
"let g:winManagerWindowLayout='TagList'
let Tlist_GainFocus_On_ToggleOpen=0
let Tlist_Use_Right_Window=1
let Tlist_Auto_Update=1

call pathogen#runtime_append_all_bundles()
filetype plugin indent on
set completeopt=longest,menu
set mouse=n

syntax on
set background=dark
"colorscheme solarized 
colorscheme custom 
"colorscheme darkburn 

set fileencoding=utf-8
"let &termencoding=&encoding
set fileencodings=utf-8,gbk,cp936,euc-cn,big5,latin1


autocmd BufReadPost *
     \ if line("'\"") > 1 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

if !exists(":DiffOrig")
      command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
              \ | wincmd p | diffthis
endif

"cscope
"set cscopequickfix=s-,c-,d-,i-,t-,e-
cs add ./cscope.out
cs add /usr/include/cscope.out /usr/include

"nmap: map in normal mod, imap:map in insert mod, vmap:map in vusual mod,
"noremap :no recursive map
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-s> :update<CR>
nnoremap <C-q> :qa<CR>
nmap <F1> :tabprevious<CR>
nmap <F2> :tabnext<CR>
nmap <F3> :vs<CR>
nmap <F4> :q<CR>
nmap <F5> :ConqueTermVSplit bash<CR>
nmap <F6> :cn<CR>
nmap <F7> :cp<CR>
nmap <F8> :cw<CR>
nmap <silent> <F12> :AV<CR>
nmap <C-n> :tab split<CR>
nmap wm :Tlist<CR>
nmap * *N
nnoremap j jzz
nnoremap k kzz
nmap ak :cs add /disk2/bill.wang/work/trunk/kernel_2.6.32.11/cscope.out /disk2/bill.wang/work/trunk/kernel_2.6.32.11<CR>

cmap w!! w !sudo tee % > /dev/null 


let g:SuperTabRetainCompletionType=2
let g:SuperTabDefaultCompletionType="<C-X><C-O>"
"let g:LookupFile_TagExpr = '"/home/wxf/work/allinone_s1_b20x/tags"' 
"let g:LookupFile_TagExpr = '"/home/wxf/work/allinone_s3/tags"' 

"inoremap [ []<Esc>i
"inoremap ( ()<Esc>i
"inoremap { {}<Esc>i
"inoremap < <><Esc>i
"inoremap > <><Esc>i
"inoremap ' ''<Esc>i
"inoremap " ""<Esc>i

"NERDTree
let NERDChristmasTree=1
let NERDTreeAutoCenter=1
let NERDTreeShowBookmarks=1
let NERDTreeShowLineNumbers=1
nnoremap wn  :NERDTreeTabsToggle<cr>

"NERD Commenter
let mapleader=","

"CtrlP
let g:ctrlp_cmd = 'CtrlP ./'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_by_filename = 1
let g:ctrlp_match_window = 'results:50'

"supertab
"let g:SuperTabDefaultCompletionType = "<c-x><c-u>"

"airline
"set laststatus=2

highlight DiffAdd cterm=bold ctermfg=black ctermbg=darkblue gui=none guifg=bg guibg=Red
highlight DiffDelete cterm=bold ctermfg=black ctermbg=darkgreen gui=none guifg=bg guibg=Yellow
highlight DiffChange cterm=bold ctermfg=black ctermbg=darkcyan gui=none guifg=bg guibg=Green
highlight DiffText cterm=bold ctermfg=black ctermbg=darkred gui=none guifg=bg guibg=Blue
