# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="gallifrey"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
 HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git z ls)
plugins=(z ls)

# User configuration

#export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

#PROMPT='%{$fg_bold[red]%}%p %{$fg[red]%}%d %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%}% %{$reset_color%}> '
#PROMPT='%{$fg_bold[green]%}%p%{$fg[cyan]%}%d %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%}% %{$reset_color%}> '
#PROMPT='%{$fg_bold[red]%}'
#PROMPT='%{$fg_bold[red]%} %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -AF --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# alias vim='/home/wang.xiaofeng/work/dotfiles/bin/vim7.4_x86'
# alias vimdiff='/home/wang.xiaofeng/work/dotfiles/bin/vimdiff'
# some more ls aliases
alias ll='ls -AlFh'
alias l='ls -CF'
alias h='history | tail -n 25'
alias cp='cp -vi'
alias cu='cscope -Rbq'
alias ds='du -s'
alias ga='git add'
alias gd='git diff'
alias gco='git checkout'
alias gst='git status'
alias gci='git commit'
alias gitpush='git push origin master'
alias gpush='git push origin master'
alias gitpull='git pull'
alias gpull='git pull'
alias rm='trash-put'
alias ta='tmux attach'
alias free='free -h'
alias less='less -g'
alias -s html=mate
alias -s c=vim
alias -s txt=vim

lua_enable=`vim --version | grep +lua`
lua_enable="notdetect"
if [ -z "$lua_enable" ]; then
        export VIMRUNTIME=/usr/share/vim/vim74
        platform=`uname -a | grep x86_64`
        if [ -z "$platform" ]; then
                #alias vim='~/dotfiles/bin/vim7.4_x86'
                [ ! -f ~/dotfiles/bin/vim ] && ln -sf ~/dotfiles/bin/vim7.4_x86 ~/dotfiles/bin/vim
                [ ! -f ~/dotfiles/bin/vimdiff ] && ln -sf ~/dotfiles/bin/vim7.4_x86 ~/dotfiles/bin/vimdiff
        else
                #alias vim='~/dotfiles/bin/vim7.4_x64'
                [ ! -f ~/dotfiles/bin/vim ] && ln -sf ~/dotfiles/bin/vim7.4_x64 ~/dotfiles/bin/vim
                [ ! -f ~/dotfiles/bin/vimdiff ] && ln -sf ~/dotfiles/bin/vim7.4_x64 ~/dotfiles/bin/vimdiff
        fi
fi

#export PATH=~/dotfiles/bin:$PATH:/opt/LSDK/build/gcc-4.3.3/build_mips/staging_dir/usr/bin/
export PATH=~/dotfiles/bin:$PATH
export EDITOR=vim
export BLOCKSIZE=K
export HISTTIMEFORMAT='(%Y-%m-%d) (%H:%M:%S)  '
export PAGER='less -g'

#disable terminal map, c+s etc.
stty -ixon

source ~/.oh-my-zsh/plugins/incr/incr.zsh
